# Generated by Django 4.0.6 on 2022-11-26 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='default.png', upload_to='user_avatars', verbose_name='Аватарка'),
        ),
    ]
