# Generated by Django 4.0.6 on 2022-11-13 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
    ]
