# Generated by Django 4.0.6 on 2022-11-13 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0002_alter_note_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['complete', 'creating_date'], 'verbose_name': 'Заметка', 'verbose_name_plural': 'Заметки'},
        ),
        migrations.RemoveField(
            model_name='note',
            name='date',
        ),
        migrations.AddField(
            model_name='note',
            name='complete',
            field=models.BooleanField(default=False, verbose_name='Выполнение'),
        ),
        migrations.AddField(
            model_name='note',
            name='creating_date',
            field=models.DateTimeField(null=True, verbose_name='Дата'),
        ),
        migrations.AddField(
            model_name='note',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
