# Generated by Django 4.0.6 on 2022-11-13 19:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0003_alter_note_options_remove_note_date_note_complete_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Note',
            new_name='Task',
        ),
    ]
