# Generated by Django 4.0.6 on 2022-11-15 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_rename_note_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='complete_date',
            field=models.DateTimeField(null=True, verbose_name='Дата выполненения'),
        ),
        migrations.AlterField(
            model_name='task',
            name='creating_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата'),
        ),
    ]
